blank_issues_enabled: false
contact_links:
  - name: BUG OR FEATURE REQUEST FOR COMPANION ITSELF
    url: https://github.com/bitfocus/companion/issues
    about: Report it against Companion itself to notify the relevant maintainers.
